---
titleStat: '[a§aTop§bPlayers§f] §9Estadistica de el jugador {player}:'
userNotExist: '[a§aTop§bPlayers§f] §eNo existe el jugador'
killTitle: §eCantidad de veces §cMatado
killElement: §2{player} - §cEliminado §7{value}
killCount: 5
deathTitle: §eCantidad de §cMuertes
deathElement: '§2{player} - §cMuerto §7{value} '
deathCount: 5
breakTitle: '§eBloques §cQuitados:'
breakElement: §2{player} - §cQuitados §7{value}
breakCount: 5
placeTitle: '§eCantidad de §cCaidas:'
placeElement: §2{player} - §cCaidas §7{value}
placeCount: 5
autoUpdate: 300
coords:
  kill:
    x: 527.000000
    "y": 66.500000
    z: -120.000000
    level: skypvp
...
